---
apiVersion: v1
kind: Namespace
metadata:
  name: geode
  labels:
    app.kubernetes.io/name: geode
    app.kubernetes.io/component: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/name: geode-apps
    app.kubernetes.io/component: applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: observability
